// <auto-generated />
namespace Televote.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class VotingTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VotingTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202102141601578_Voting.Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
